Repository freshdesk/nucleus, pull requests merged in 2020-03, with the labels that each got.

#140 feat(docs): Interactive playground component
  packages/@nucleus/app/styles/doc/_icon.scss
  packages/@nucleus/app/styles/doc/_playground.scss
  packages/@nucleus/app/styles/nucleus-docs.scss
  packages/@nucleus/tests/dummy/app/components/docs-playground.js
  packages/@nucleus/tests/dummy/app/components/docs-playground/code.js
  packages/@nucleus/tests/dummy/app/components/docs-playground/preview.js
  packages/@nucleus/tests/dummy/app/components/docs-playground/props.js
  packages/@nucleus/tests/dummy/app/components/nucleus-button/playground.js
  packages/@nucleus/tests/dummy/app/components/nucleus-icon/demo-1.js
  packages/@nucleus/tests/dummy/app/components/nucleus-icon/playground.js
  packages/@nucleus/tests/dummy/app/components/nucleus-inline-banner/playground.js
  packages/@nucleus/tests/dummy/app/constants/icons.js
  packages/@nucleus/tests/dummy/app/helpers/eq.js
  packages/@nucleus/tests/dummy/app/templates/components/docs-playground.hbs
  packages/@nucleus/tests/dummy/app/templates/components/docs-playground/code.hbs
  packages/@nucleus/tests/dummy/app/templates/components/docs-playground/preview.hbs
  packages/@nucleus/tests/dummy/app/templates/components/docs-playground/props.hbs
  packages/@nucleus/tests/dummy/app/templates/components/nucleus-button/playground.hbs
  packages/@nucleus/tests/dummy/app/templates/components/nucleus-icon/demo-1.hbs
  packages/@nucleus/tests/dummy/app/templates/components/nucleus-icon/playground.hbs
  packages/@nucleus/tests/dummy/app/templates/components/nucleus-inline-banner/playground.hbs
  packages/@nucleus/tests/dummy/app/templates/docs/components/nucleus-button.md
  packages/@nucleus/tests/dummy/app/templates/docs/components/nucleus-inline-banner.md
  packages/@nucleus/tests/dummy/app/templates/docs/foundation/nucleus-icon.md
  packages/@nucleus/tests/dummy/app/utils/copy-to-clipboard.js
  packages/@nucleus/tests/dummy/app/utils/playground.js
  packages/button/addon/components/nucleus-button.js
Labels: enhancement

#148 fix(modal): Fixes bugs for focus-trap and autofocus
  packages/@nucleus/tests/dummy/app/templates/components/nucleus-modal/demo-3.hbs
  packages/core/app/styles/global/animations/_css-transitions.scss
  packages/modal/addon/components/nucleus-modal.js
  packages/modal/addon/components/nucleus-modal/dialog.js
  packages/modal/addon/constants/nucleus-modal.js
  packages/modal/package-lock.json
Labels: bugfix

#152 chore(nucleus): Nucleus now lives in the Dark!
  packages/@nucleus/app/styles/doc/_custom-addon-theme.scss
  packages/@nucleus/app/styles/doc/_custom-syntax-highlight.scss
  packages/@nucleus/app/styles/doc/_dark-mode-theme.scss
  packages/@nucleus/app/styles/nucleus-docs.scss
  packages/@nucleus/public/assets/icons/dark.svg
  packages/@nucleus/public/assets/icons/light.svg
  packages/@nucleus/tests/dummy/app/components/theme-toggle.js
  packages/@nucleus/tests/dummy/app/templates/application.hbs
  packages/@nucleus/tests/dummy/app/templates/components/nucleus-icon/demo-1.hbs
  packages/@nucleus/tests/dummy/app/templates/components/theme-toggle.hbs
Labels: cosmetics, enhancement

#154 fix(modal): fixes positioning of elements
  packages/modal/addon/components/nucleus-slider.js
  packages/modal/addon/styles/addon.scss
  packages/modal/addon/styles/components/_nucleus-modal.scss
  packages/modal/addon/templates/components/nucleus-confirm-dialog.hbs
  packages/modal/addon/templates/components/nucleus-modal.hbs
  packages/modal/addon/templates/components/nucleus-slider.hbs
  packages/modal/ember-backstop/backstop_data/bitmaps_reference/ember-backstoptest_Integration__Component__nucleus-modal__visual_regression_for_large_confirm_dialog__assert0_0_document_0_webview.png
  packages/modal/ember-backstop/backstop_data/bitmaps_reference/ember-backstoptest_Integration__Component__nucleus-modal__visual_regression_for_modal__assert0_0_document_0_webview.png
  packages/modal/ember-backstop/backstop_data/bitmaps_reference/ember-backstoptest_Integration__Component__nucleus-modal__visual_regression_for_normal_confirm_dialog__assert0_0_document_0_webview.png
  packages/modal/ember-backstop/backstop_data/bitmaps_reference/ember-backstoptest_Integration__Component__nucleus-modal__visual_regression_for_slider__assert0_0_document_0_webview.png
Labels: bugfix
